[package]
name = "rblog"
version = "0.3.0"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2018"
license = "MIT"
description = "Blog app"

build = "src/build.rs"

[build-dependencies]
ructe = "0.11.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
async-std = { version = "1.6.0", features = ["attributes"] }
chrono = { version = "0.4.11", features = ["serde"] }
dotenv = "0.15.0"
itertools = "0.9.0"
serde = { version = "1.0.110", features = ["derive"] }
serde_yaml = "0.8.11"
slug = "0.1.4"
tide = "0.10.0"
