[package]
name = "rblog"
version = "0.7.0"
authors = ["Prabir Shrestha <mail@prabir.me>"]
edition = "2018"
license = "MIT"
description = "Blog app"
repository = "https://github.com/prabirshrestha/rblog"

build = "src/build.rs"

[build-dependencies]
ructe = { version = "0.11.4", features = ["sass", "mime03"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
async-std = { version = "1.6.1", features = ["attributes"] }
chrono = { version = "0.4.11", features = ["serde"] }
dotenv = "0.15.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_yaml = "0.8.13"
slug = "0.1.4"
tide = "0.11.0"
mime = "0.3.16"
comrak = "0.7.0"
